### ISSUE TITLE
Laggy UI

### ISSUE THREAD

**Issue by Usamaliaquat123** [5-StarDesigners/Equipment-Checker#2]
When the application is populated with mutliple offline inspections and once the user goes online, the inspections are submitted to the database. During this process the app is very unresponsive and sometimes the UI Elements get misplaced as well resulting in a very bad ui experience. Moreover, created inspections are appearing more than once on the previous inspections page.

**Comment by srizvi-official** [comment]
Team,

Project - Cheif Safety App

Problem

When the application is populated with mutliple offline inspections and once the user goes online, the inspections are submitted to the database. During this process the app is very unresponsive and sometimes the UI Elements get misplaced as well resulting in a very bad ui experience. Moreover, created inspections are appearing more than once on the previous inspections page.

Answer

Answer to your questions is web workers in javascript which are specially designed for background synchronization.

Web Worker

When executing scripts in an HTML page, the page becomes unresponsive until the script is finished.

A web worker is a JavaScript that runs in the background, independently of other scripts, without affecting the performance of the page. You can continue to do whatever you want: clicking, selecting things, etc., while the web worker runs in the background.



Here is the example how to use it in ionic: https://www.javascripttuts.com/how-to-use-web-workers-with-ionic-in-one-go/



Used it for offline storage data sync that will address the problem.

Apart from that duplicating records could be separate problem check whether API hits twice (check from network traffic tab) or could be issue from backend (but, i doubt because earlier it was working fine)



Implement it and let me know.

**Comment by Usamaliaquat123** [comment]
@srizvi-official @syedatifgd looks like the problem is with ionic whatever we are using localstorage or any local SQlite package or webWorker lib . The problem is same actually in our application ionic localstorage saving large amount of data including base64 images and inspections that client created in offline state. That's why application goes to unresponsive state when we are online or offline. @srizvi-official  please provide any solution...

**Comment by srizvi-official** [comment]
I provided solution above  "Web Workers" read it, its only way of doing it.

**Comment by Usamaliaquat123** [comment]
**Solution :** 
@srizvi-official I know but web worker takes time to implement. We are skipping base64 methods getting inspection's and save into localstorage just getting text not base64 string.

**Creating Inspections**
At the time of creating inspection offline inspections submited sucessfully (with base64 String) and saved in to localdb. When internet is connected local inspection array send to the backend and cleared inspections array.

**Now app is working fine in offline and online status**
